using Volo.Abp;

namespace ProjectMicrosserveicesAbp.EntityFrameworkCore;

public abstract class ProjectMicrosserveicesAbpEntityFrameworkCoreTestBase : ProjectMicrosserveicesAbpTestBase<ProjectMicrosserveicesAbpEntityFrameworkCoreTestModule>
{

}
